# Generated by Django 4.1.4 on 2023-01-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fileName", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=50)),
                ("timeDate", models.DateTimeField(null=True)),
                ("description", models.TextField(max_length=100)),
            ],
        ),
    ]
