# Generated by Django 4.1.4 on 2023-01-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bannaoapp", "0003_orders_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="orderedBy",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
