# Generated by Django 4.1.4 on 2023-01-08 19:36

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bannaoapp", "0004_orders_orderedby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="orderedBy",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name=django.contrib.auth.models.User,
            ),
        ),
    ]
