# Generated by Django 4.1.4 on 2023-01-08 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bannaoapp", "0005_alter_orders_orderedby"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="orderedBy",
        ),
        migrations.AddField(
            model_name="orders",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
