# Generated by Django 4.1.4 on 2023-01-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bannaoapp", "0007_remove_orders_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="orderedBy",
            field=models.CharField(default="", max_length=50),
        ),
    ]
