# Generated by Django 4.1.4 on 2023-01-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bannaoapp", "0008_orders_orderedby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="orderedBy",
            field=models.CharField(max_length=50),
        ),
    ]
