# Generated by Django 4.1.4 on 2023-01-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bannaoapp", "0012_alter_orders_orderedby"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="orders",
            table="orders",
        ),
    ]
