# Generated by Django 4.1.4 on 2023-01-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bannaoapp", "0013_alter_orders_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="image",
            new_name="file",
        ),
    ]
