# Generated by Django 4.1.4 on 2023-01-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bannaoapp", "0014_rename_image_orders_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="calculatedPrice",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="volume",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
